export default [
  {
    id: 1,
    question: "What is the largest country in Africa by area? ",
    answer1: "Algeria",
    answer2: "South Africa",
    answer3: "Nigeria",
    correctAnswer: "Algeria",
    isAnswered: false,
  },
  {
    id: 2,
    question: "What is the most populous country in Africa? ",
    answer1: "Nigeria",
    answer2: "Egypt",
    answer3: "Sudan",
    correctAnswer: "Nigeria",
    isAnswered: false,
  },
  {
    id: 3,
    question: "What is the capital city of Morocco?",
    answer1: "Casablanca",
    answer2: "Fez",
    answer3: "Rabat",
    correctAnswer: "Rabat",
    isAnswered: false,
  },
  {
    id: 4,
    question: "What is the capital city of Kenya?",
    answer1: "Mombasa",
    answer2: "Kisumu",
    answer3: "Nairobi",
    correctAnswer: "Nairobi",
    isAnswered: false,
  },
  {
    id: 5,
    question: "What is the longest river in Africa?",
    answer1: "The Nile River",
    answer2: "Congo River",
    answer3: "Grootrivier",
    correctAnswer: "The Nile River",
    isAnswered: false,
  },
  {
    id: 6,
    question: "What is the largest desert in Africa?",
    answer1: "Sahara Desert",
    answer2: "Libyan Desert",
    answer3: "Namib Desert",
    correctAnswer: "Sahara Desert",
    isAnswered: false,
  },
  {
    id: 7,
    question: "What is the highest mountain in Africa?",
    answer1: "Mount Kilimanjaro",
    answer2: "Mount Meru",
    answer3: "Mount Guna",
    correctAnswer: "Mount Kilimanjaro",
    isAnswered: false,
  },
  {
    id: 8,
    question: "N'Djamena is the capital of which of the following countries?",
    answer1: "Chad",
    answer2: "Ghana",
    answer3: "Uganda",
    correctAnswer: "Chad",
    isAnswered: false,
  },
  {
    id: 9,
    question: "In which year was Johannesburg found?",
    answer1: "1902",
    answer2: "1861",
    answer3: "1886",
    correctAnswer: "1886",
    isAnswered: false,
  },
  {
    id: 10,
    question: "Which river is also called the father of African rivers?",
    answer1: "Kasai River",
    answer2: "Uele River",
    answer3: "Nile River",
    correctAnswer: "Nile River",
    isAnswered: false,
  },
  {
    id: 11,
    question: "Which is the highest mountain peak of the Sahara?",
    answer1: "Mount Koussi",
    answer2: "Mount Elgon",
    answer3: "Mount Virunga",
    correctAnswer: "Mount Koussi",
    isAnswered: false,
  },
  {
    id: 12,
    question: "Which country was formerly called South West Africa?",
    answer1: "Mali",
    answer2: "Tunisia",
    answer3: "Namibia",
    correctAnswer: "Namibia",
    isAnswered: false,
  },
  {
    id: 13,
    question:
      "Which African desert name means 'an area where there is nothing'?",
    answer1: "Karoo Desert",
    answer2: "Namib Desert",
    answer3: "Kalahari Desert",
    correctAnswer: "Namib Desert",
    isAnswered: false,
  },
  {
    id: 14,
    question: "Which language is spoken on the east coast of Africa?",
    answer1: "Songhay language",
    answer2: "Swahili language",
    answer3: "Malagasy language",
    correctAnswer: "Swahili language",
    isAnswered: false,
  },
  {
    id: 15,
    question: "Which African river flows into the Indian Ocean?",
    answer1: "Kowie River",
    answer2: "Luangwa River",
    answer3: "Zambezi River",
    correctAnswer: "Zambezi River",
    isAnswered: false,
  },
  {
    id: 16,
    question: "What body of water connects the Mediterranean and the Red seas?",
    answer1: "Gulf of Aden",
    answer2: "Seuz Canal",
    answer3: "Benue River",
    correctAnswer: "Seuz Canal",
    isAnswered: false,
  },
  {
    id: 17,
    question: "Which continent lies in all four hemispheres?",
    answer1: "Asia",
    answer2: "Antarctica",
    answer3: "Africa",
    correctAnswer: "Africa",
    isAnswered: false,
  },
  {
    id: 18,
    question:
      "Which landlocked African country is nicknamed 'the land of a thousand hills'?",
    answer1: "Rwanda",
    answer2: "Senegal",
    answer3: "Swaziland",
    correctAnswer: "Rwanda",
    isAnswered: false,
  },
  {
    id: 19,
    question: "Which is the easternmost extension of Africa?",
    answer1: "Somali",
    answer2: "Tigray Region",
    answer3: "Horn of Africa",
    correctAnswer: "Horn of Africa",
    isAnswered: false,
  },
  {
    id: 20,
    question: "Which is the smallest non-island country in Africa?",
    answer1: "The Gambia",
    answer2: "Tanzania",
    answer3: "Mozambique",
    correctAnswer: "The Gambia",
    isAnswered: false,
  },
  {
    id: 21,
    question: "Which of the following country lies on the Horn of Africa?",
    answer1: "Philippines",
    answer2: "Serbia",
    answer3: "Ethiopia",
    correctAnswer: "Ethiopia",
    isAnswered: false,
  },
  {
    id: 22,
    question: "Which is the largest ethnic group in South Africa?",
    answer1: "Zulu",
    answer2: "Hutu",
    answer3: "Bantu",
    correctAnswer: "Zulu",
    isAnswered: false,
  },
  {
    id: 23,
    question: "Serengeti National Park is in which country?",
    answer1: "Niger",
    answer2: "Tanzania",
    answer3: "Kenya",
    correctAnswer: "Tanzania",
    isAnswered: false,
  },
  {
    id: 24,
    question: "Where is Victoria Falls located?",
    answer1: "Zambia",
    answer2: "Paraguay",
    answer3: "Romania",
    correctAnswer: "Zambia",
    isAnswered: false,
  },
  {
    id: 25,
    question: "In what part of Africa is the Cape of Good Hope located?",
    answer1: "Morocco",
    answer2: "South Sudan",
    answer3: "South Africa",
    correctAnswer: "South Africa",
    isAnswered: false,
  },
  {
    id: 26,
    question:
      "What historic city, located in the centre of the fertile Haouz Plain south of the Tennsift River, is the major city of central Morocco?",
    answer1: "Casablanca",
    answer2: "Marrakech",
    answer3: "Rabat",
    correctAnswer: "Marrakech",
    isAnswered: false,
  },
  {
    id: 27,
    question: "Which is the largest lake in Ethiopia?",
    answer1: "Lake Tana",
    answer2: "Ziway Lake",
    answer3: "Lake Turkana",
    correctAnswer: "Lake Tana",
    isAnswered: false,
  },
  {
    id: 28,
    question: "Which country is bordered by Burkina Faso, Nigeria, and Togo",
    answer1: "Sierra Leone",
    answer2: "Benin",
    answer3: "Japan",
    correctAnswer: "Benin",
    isAnswered: false,
  },
  {
    id: 29,
    question: "Which is the highest peak in Africa?",
    answer1: "Mount Batian",
    answer2: "Toubkal",
    answer3: "Kilimanjaro",
    correctAnswer: "Kilimanjaro",
    isAnswered: false,
  },
  {
    id: 30,
    question: "In which country do we find Winam Gulf?",
    answer1: "Guam",
    answer2: "Kenya",
    answer3: "Argentina",
    correctAnswer: "Kenya",
    isAnswered: false,
  },
  {
    id: 31,
    question: "What is the lowest point on the African continent?",
    answer1: "Lake Mweru",
    answer2: "Lake Albert",
    answer3: "Lake Assal",
    correctAnswer: "Lake Assal",
    isAnswered: false,
  },
  {
    id: 32,
    question: "Which country is the chief home of the Shona people?",
    answer1: "Zimbabwe",
    answer2: "Tanzania",
    answer3: "Kenya",
    correctAnswer: "Zimbabwe",
    isAnswered: false,
  },
  {
    id: 33,
    question:
      "Which lake is the largest lake in Africa and the main reservoir of the Nile?",
    answer1: "Lake Malawi",
    answer2: "Lake Victoria",
    answer3: "Lake Chad",
    correctAnswer: "Lake Victoria",
    isAnswered: false,
  },
  {
    id: 34,
    question: "Which is the highest waterfall in Africa?",
    answer1: "Tugela Falls",
    answer2: "Owu Falls",
    answer3: "Kagera Falls",
    correctAnswer: "Tugela Falls",
    isAnswered: false,
  },
  {
    id: 35,
    question: "Which of the following separates Africa from Europe?",
    answer1: "Red Sea",
    answer2: "Arabian Sea",
    answer3: "Mediterranean Sea",
    correctAnswer: "Mediterranean Sea",
    isAnswered: false,
  },
  {
    id: 36,
    question: "Which country is completely surrounded by South Africa?",
    answer1: "Lesotho",
    answer2: "Liberia",
    answer3: "Madagascar",
    correctAnswer: "Lesotho",
    isAnswered: false,
  },
  {
    id: 37,
    question: "Which of the following is not a border of the Sahara Desert?",
    answer1: "Atlantic Ocean",
    answer2: "Bering Sea",
    answer3: "Pacific Ocean",
    correctAnswer: "Pacific Ocean",
    isAnswered: false,
  },
  {
    id: 38,
    question: "Ouagadougou is the capital of which African nation?",
    answer1: "Burkina Faso",
    answer2: "Gabon",
    answer3: "Somalia",
    correctAnswer: "Burkina Faso",
    isAnswered: false,
  },
];
