export default [
  {
    id: 1,
    question: "Asya'nın en büyük kömür üreticisi hangisidir?",
    answer1: "Çin",
    answer2: "Hindistan",
    answer3: "Türkiye",
    correctAnswer: "Çin",
    isAnswered: false,
  },
  {
    id: 2,
    question: "Asya'nın en büyük petrol üreticisi hangisidir?",
    answer1: "Japonya",
    answer2: "Kuzey Kore",
    answer3: "Suudi Arabistan",
    correctAnswer: "Suudi Arabistan",
    isAnswered: false,
  },
  {
    id: 3,
    question: "Asya Kıtasında en çok konuşulan dil hangisidir?",
    answer1: "Türkçe",
    answer2: "Japonca",
    answer3: "Mandarin Çincesi",
    correctAnswer: "Mandarin Çincesi",
    isAnswered: false,
  },
  {
    id: 4,
    question: "Avrupa'yı Asya'ya bağlayan Galata Köprüsü hangi ülkededir??",
    answer1: "Rusya",
    answer2: "Türkiye",
    answer3: "Yunanistan",
    correctAnswer: "Türkiye",
    isAnswered: false,
  },
  {
    id: 5,
    question: "Aşağıdakilerden hangisi bir şehir devletidir?",
    answer1: "Tayvan",
    answer2: "Vietnam",
    answer3: "Singapur",
    correctAnswer: "Singapur",
    isAnswered: false,
  },
  {
    id: 6,
    question: "Taipei hangi ülkenin başkentidir?",
    answer1: "Tayvan",
    answer2: "Tayland",
    answer3: "Vietnam",
    correctAnswer: "Tayvan",
    isAnswered: false,
  },
  {
    id: 7,
    question: "Kim Jong-un hangi ülkenin lideridir?",
    answer1: "Tayland",
    answer2: "Güney Kore",
    answer3: "Kuzey Kore",
    correctAnswer: "Kuzey Kore",
    isAnswered: false,
  },
  {
    id: 8,
    question: "Vientiane hangi ülkenin başkentidir?",
    answer1: "Yemen",
    answer2: "Laos",
    answer3: "Lübnan",
    correctAnswer: "Laos",
    isAnswered: false,
  },
  {
    id: 9,
    question: "Amman hangi ülkenin başkentidir?",
    answer1: "Ürdün",
    answer2: "İsrail",
    answer3: "Myanmar",
    correctAnswer: "Ürdün",
    isAnswered: false,
  },
  {
    id: 10,
    question: "Türkmenistan'ın ulusal bayrağındaki baskın renk hangisidir?",
    answer1: "Beyaz",
    answer2: "Mavi",
    answer3: "Yeşil",
    correctAnswer: "Yeşil",
    isAnswered: false,
  },
  {
    id: 11,
    question: "Çin Seddinin uzunluğu kaç km'dir?",
    answer1: "21.020 km",
    answer2: "21.196 km",
    answer3: "22.520 km",
    correctAnswer: "21.196 km",
    isAnswered: false,
  },
  {
    id: 12,
    question: "Siyam hangi ülkenin eski adıdır?",
    answer1: "Tayland",
    answer2: "Filipinler",
    answer3: "Tayvan",
    correctAnswer: "Tayland",
    isAnswered: false,
  },
  {
    id: 13,
    question: "Lazkiye limanı hangi ülkededir?",
    answer1: "Yemen",
    answer2: "Lübnan",
    answer3: "Suriye",
    correctAnswer: "Suriye",
    isAnswered: false,
  },
  {
    id: 14,
    question: "Aşağıdakilerden hangisi bir Asya ülkesi olarak kabul edilir?",
    answer1: "Litvanya",
    answer2: "Burundi",
    answer3: "Özbekistan",
    correctAnswer: "Özbekistan",
    isAnswered: false,
  },
  {
    id: 15,
    question: "Pakistan'ın ulusal bayrağındaki baskın renk hangisidir?",
    answer1: "Siyah",
    answer2: "Kırmızı",
    answer3: "Yeşil",
    correctAnswer: "Yeşil",
    isAnswered: false,
  },
  {
    id: 16,
    question: "Asya'daki en büyük sinema endüstrisi nedir?",
    answer1: "Bollywood",
    answer2: "Hollywood",
    answer3: "Yesilcam",
    correctAnswer: "Bollywood",
    isAnswered: false,
  },
  {
    id: 17,
    question: "Asya'daki en uzun nehir hangisidir?",
    answer1: "Yangtze Nehri",
    answer2: "Sarı Nehir",
    answer3: "Lena Nehri",
    correctAnswer: "Yangtze Nehri",
    isAnswered: false,
  },
  {
    id: 18,
    question: "Güney Kore'nin başkenti neresidir?",
    answer1: "Seul",
    answer2: "Tokyo",
    answer3: "Yamaha",
    correctAnswer: "Seul",
    isAnswered: false,
  },
  {
    id: 19,
    question: "Hindistan'ın başkenti neresidir?",
    answer1: "Mumbai",
    answer2: "Varanasi",
    answer3: "Yeni Delhi",
    correctAnswer: "Yeni Delhi",
    isAnswered: false,
  },
  {
    id: 20,
    question: "Asya'nın en yüksek dağı hangisidir?",
    answer1: "Cho Oyu Dağı",
    answer2: "Everest Dağı",
    answer3: "Makalu Dağı",
    correctAnswer: "Everest Dağı",
    isAnswered: false,
  },
  {
    id: 21,
    question: "Asya'daki en büyük Müslüman ülke neresidir?",
    answer1: "Endonezya",
    answer2: "Moğolistan",
    answer3: "Rusya",
    correctAnswer: "Endonezya",
    isAnswered: false,
  },
  {
    id: 22,
    question: "Asya'daki en büyük çöl nedir?",
    answer1: "Gobi Çölü",
    answer2: "Karakum Çölü",
    answer3: "Ordos Çölü",
    correctAnswer: "Gobi Çölü",
    isAnswered: false,
  },
  {
    id: 23,
    question: "Batı Asya'nın en uzun nehri hangisidir?",
    answer1: "Tigris Nehri",
    answer2: "Fırat Nehri",
    answer3: "Kurobe Nehri",
    correctAnswer: "Fırat Nehri",
    isAnswered: false,
  },
  {
    id: 24,
    question: "Afganistan'ın başkenti neresidir?",
    answer1: "Kabul",
    answer2: "Tahran",
    answer3: "Bağdat",
    correctAnswer: "Kabul",
    isAnswered: false,
  },
  {
    id: 25,
    question: "Dünyanın en çok çay ihraç eden ülkesi hangisidir?",
    answer1: "Türkiye",
    answer2: "Çin",
    answer3: "Srilanka",
    correctAnswer: "Çin",
    isAnswered: false,
  },
  {
    id: 26,
    question: "Pekin, Çin'den geçen nehrin adı nedir?",
    answer1: "Fırat Nehri",
    answer2: "İrtiş Nehri",
    answer3: "Yongding Nehri",
    correctAnswer: "Yongding Nehri",
    isAnswered: false,
  },
  {
    id: 27,
    question:
      "Güneydoğu Asya'da bulunan dünyanın en büyük çiçeğinin adı nedir?",
    answer1: "Anemon",
    answer2: "Rafflesia",
    answer3: "Aslanağzı",
    correctAnswer: "Rafflesia",
    isAnswered: false,
  },
  {
    id: 28,
    question: "Ünlü filozof Konfüçyüs'ün doğum yeri olan ülke hangisidir?",
    answer1: "Çin",
    answer2: "Güney Kore",
    answer3: "Japonya",
    correctAnswer: "Çin",
    isAnswered: false,
  },
  {
    id: 29,
    question:
      "Dünyanın en büyük nehir adasına ev sahipliği yapan ülke hangisidir?",
    answer1: "Hindistan",
    answer2: "Çin",
    answer3: "Filipinler",
    correctAnswer: "Hindistan",
    isAnswered: false,
  },
  {
    id: 30,
    question: "Ringgit hangi Asya ülkesinin para birimidir?",
    answer1: "Sri Lanka",
    answer2: "Vietnam",
    answer3: "Malezya",
    correctAnswer: "Malezya",
    isAnswered: false,
  },
  {
    id: 31,
    question:
      "İki boyutlu ve üç boyutlu nesneler yaratmak için nesneleri kağıttan katlama sanatı nedir?",
    answer1: "kaligrafi",
    answer2: "origami",
    answer3: "decoupage",
    correctAnswer: "origami",
    isAnswered: false,
  },
  {
    id: 32,
    question:
      "Japonya'da en son 1707'de patlayan ancak jeologlar tarafından hâlâ aktif olarak sınıflandırılan yanardağ hangisidir?",
    answer1: "Rinjani Dağı",
    answer2: "Taal Volkanı",
    answer3: "Fuji Dağı",
    correctAnswer: "Fuji Dağı",
    isAnswered: false,
  },
  {
    id: 33,
    question: "Hangi dağ geçidi Kābul ile Peşaver'i birleştirir?",
    answer1: "Hayber Geçidi",
    answer2: "Shipki La",
    answer3: "Diphu Geçidi",
    correctAnswer: "Hayber Geçidi",
    isAnswered: false,
  },
  {
    id: 34,
    question: "Tsai Ing-wen hangi ülkenin ilk kadın başkanıdır?",
    answer1: "Kamboçya",
    answer2: "Tayvan",
    answer3: "Japonya",
    correctAnswer: "Tayvan",
    isAnswered: false,
  },
  {
    id: 35,
    question: "Çin bayrağının ana rengi nedir?",
    answer1: "mavi",
    answer2: "yeşil",
    answer3: "kırmızı",
    correctAnswer: "kırmızı",
    isAnswered: false,
  },
  {
    id: 36,
    question: "Aşağıdaki şehirlerden hangisi Saygon Nehri üzerindedir?",
    answer1: "Hong Kong",
    answer2: "Hanoi",
    answer3: "Ho Chi Minh Şehri",
    correctAnswer: "Ho Chi Minh Şehri",
    isAnswered: false,
  },
  {
    id: 37,
    question: "Bangladeş'in başkenti neresidir?",
    answer1: "Dakka",
    answer2: "Akra",
    answer3: "Aden",
    correctAnswer: "Dakka",
    isAnswered: false,
  },
  {
    id: 38,
    question: "Dünyadaki mevcut en eski tatlı su gölü hangisidir?",
    answer1: "Superior Gölü",
    answer2: "Victoria Gölü",
    answer3: "Baykal Gölü",
    correctAnswer: "Baykal Gölü",
    isAnswered: false,
  },
  {
    id: 39,
    question: "Myanmar'ı Çin'e bağlayan yol hangisidir?",
    answer1: "Burma Yolu",
    answer2: "Karakoram Otoyolu",
    answer3: "Appian Yolu",
    correctAnswer: "Burma yOLU",
    isAnswered: false,
  },
  {
    id: 40,
    question:
      "Aşağıdaki su kütlelerinden hangisi Asya ile Afrika kıtasını birbirinden ayırır??",
    answer1: "Arap Denizi",
    answer2: "Süveyş Kanalı",
    answer3: "Kızıl Deniz",
    correctAnswer: "Süveyş Kanalı",
    isAnswered: false,
  },
  {
    id: 41,
    question: "Endonezya hangi okyanusun altında kalıyor?",
    answer1: "Güneu",
    answer2: "Arktik",
    answer3: "Pasifik",
    correctAnswer: "Pasifik",
    isAnswered: false,
  },
  {
    id: 42,
    question: "Kamçatka Yarımadası hangi ülkededir?",
    answer1: "Rusya",
    answer2: "Turkiye",
    answer3: "Moğolistan",
    correctAnswer: "Rusya",
    isAnswered: false,
  },
  {
    id: 43,
    question: "Güneydoğu Asya'daki en uzun nehir hangisidir?",
    answer1: "Chao Phraya Nehri",
    answer2: "Mekong Nehri",
    answer3: "Salween Nehri",
    correctAnswer: "Mekong Nehri",
    isAnswered: false,
  },
  {
    id: 44,
    question: "Mekong Nehri hangi ülkenin içinden geçmez??",
    answer1: "Laos",
    answer2: "Moğolistan",
    answer3: "Çin",
    correctAnswer: "Moğolistan",
    isAnswered: false,
  },
  {
    id: 45,
    question: "Batı dünyasını Asya'ya bağlayan antik ticaret yolu hangisidir??",
    answer1: "İpek Yolu",
    answer2: "Via Maris",
    answer3: "Oregon Patikası",
    correctAnswer: "İpek Yolu",
    isAnswered: false,
  },
  {
    id: 46,
    question: "İlk Asya Oyunları hangi şehirde yapılmıştır?",
    answer1: "Yeni Delhi",
    answer2: "Jakarta",
    answer3: "Seul",
    correctAnswer: "Yeni Delhi",
    isAnswered: false,
  },
  {
    id: 47,
    question:
      "Andaman Denizi ile Güney Çin Denizi'ni birbirine bağlayan su yolu hangisidir?",
    answer1: "Aşçı Boğazı",
    answer2: "Bering Boğazı",
    answer3: "Malakka Boğazı",
    correctAnswer: "Malakka Boğazı",
    isAnswered: false,
  },

  {
    id: 48,
    question: "Güney Kore'nin en büyük liman şehri neresidir?",
    answer1: "Pusan",
    answer2: "Seul",
    answer3: "Ulsan",
    correctAnswer: "Pusan",
    isAnswered: false,
  },
  {
    id: 49,
    question: "1964 Olimpiyat Oyunlarına hangi şehir ev sahipliği yapmıştır?",
    answer1: "Barcelona",
    answer2: "Tokyo",
    answer3: "Roma",
    correctAnswer: "Tokyo",
    isAnswered: false,
  },
  {
    id: 50,
    question: "Türkiyenin başkenti neresidir",
    answer1: "Istanbul",
    answer2: "Antalya",
    answer3: "Ankara",
    correctAnswer: "Ankara",
    isAnswered: false,
  },
];
