export default [
  {
    id: 1,
    question: "What is the longest river in Europe?",
    answer1: "Saone",
    answer2: "Volga River",
    answer3: "River Shannon",
    correctAnswer: "Volga River",
    isAnswered: false,
  },
  {
    id: 2,
    question: "What is the largest lake in Europe? ",
    answer1: "Lake Ohrid",
    answer2: "Lake Lugano",
    answer3: "Lake Ladoga",
    correctAnswer: "Lake Ladoga",
    isAnswered: false,
  },
  {
    id: 3,
    question: "What is the highest mountain in Europe? ",
    answer1: "Mount Elbrus",
    answer2: "Mont Blanc",
    answer3: "Dolomit Mountains",
    correctAnswer: "Mount Elbrus",
    isAnswered: false,
  },
  {
    id: 4,
    question: "What is the most populous city in Europe? ",
    answer1: "Munich",
    answer2: "Istanbul",
    answer3: "Paris",
    correctAnswer: "Istanbul",
    isAnswered: false,
  },
  {
    id: 5,
    question: "Which country is the westernmost in Europe?",
    answer1: "Spain",
    answer2: "Austria",
    answer3: "Portugal",
    correctAnswer: "Portugal",
    isAnswered: false,
  },
  {
    id: 6,
    question: "Which country is the northernmost in Europe?",
    answer1: "Sweden",
    answer2: "Norway",
    answer3: "Denmark",
    correctAnswer: "Norway",
    isAnswered: false,
  },
  {
    id: 7,
    question: "What is the largest island in Europe?",
    answer1: "Great Britain",
    answer2: "Ireland",
    answer3: "Greece",
    correctAnswer: "Great Britain",
    isAnswered: false,
  },
  {
    id: 8,
    question: "What is the largest port in Europe?",
    answer1: "Rotterdam Port",
    answer2: "Antwerp Port",
    answer3: "Bergen Port",
    correctAnswer: "Rotterdam Port",
    isAnswered: false,
  },
  {
    id: 9,
    question: "What is the smallest country in the European Union?",
    answer1: "San Marino",
    answer2: "Andorra",
    answer3: "Malta",
    correctAnswer: "Malta",
    isAnswered: false,
  },
  {
    id: 10,
    question: "What is the second largest lake in Europe? ",
    answer1: "Lake Onega",
    answer2: "Lake Plansee",
    answer3: "Lake Vanern",
    correctAnswer: "Lake Onega",
    isAnswered: false,
  },
  {
    id: 11,
    question: "What is the smallest country in Europe by land area? ",
    answer1: "Andorra",
    answer2: "Vatican City",
    answer3: "Monaco",
    correctAnswer: "Vatican City",
    isAnswered: false,
  },
  {
    id: 12,
    question: "What is the capital city of Croatia? ",
    answer1: "Zagreb",
    answer2: "Dubrovnik",
    answer3: "Zadar",
    correctAnswer: "Zagreb",
    isAnswered: false,
  },
  {
    id: 13,
    question: "What is the capital city of Cyprus?",
    answer1: "Famagusta",
    answer2: "Limassol",
    answer3: "Nicosia",
    correctAnswer: "Nicosia",
    isAnswered: false,
  },
  {
    id: 14,
    question: "What is the capital city of Denmark?",
    answer1: "Copenhagen",
    answer2: "Odense",
    answer3: "Aarhus",
    correctAnswer: "Copenhagen",
    isAnswered: false,
  },
  {
    id: 15,
    question: "What is the capital city of Ireland?",
    answer1: "Cork",
    answer2: "Dublin",
    answer3: "Belfast",
    correctAnswer: "Dublin",
    isAnswered: false,
  },
  {
    id: 16,
    question: "What is the capital city of Latvia?",
    answer1: "Riga",
    answer2: "Daugavpils",
    answer3: "Jelgava",
    correctAnswer: "Riga",
    isAnswered: false,
  },
  {
    id: 17,
    question:
      "Which country in Europe is known for its beaches along the Algarve coastline? ",
    answer1: "Portugal",
    answer2: "Spain",
    answer3: "Andorra",
    correctAnswer: "Portugal",
    isAnswered: false,
  },
  {
    id: 18,
    question:
      "Which country in Europe is famous for its iconic blue and white ceramics called Delftware?",
    answer1: "Italy",
    answer2: "France",
    answer3: "Netherlands",
    correctAnswer: "Netherlands",
    isAnswered: false,
  },
  {
    id: 19,
    question:
      "What is the name of the river that flows through Prague, Czech Republic?",
    answer1: "The Vltava River",
    answer2: "The Po River",
    answer3: "Douro River",
    correctAnswer: "The Vltava River",
    isAnswered: false,
  },
  {
    id: 20,
    question:
      "Which country is known for its world-class ski resorts and the Matterhorn peak? ",
    answer1: "France",
    answer2: "Norway",
    answer3: "Switzerland",
    correctAnswer: "Switzerland",
    isAnswered: false,
  },
  {
    id: 21,
    question: "Which country is home to the world's largest flower auction? ",
    answer1: "Netherlands",
    answer2: "Greece",
    answer3: "Belgium",
    correctAnswer: "Netherlands",
    isAnswered: false,
  },
  {
    id: 22,
    question: "What is the capital of Belarus?",
    answer1: "Kiev",
    answer2: "Moscow",
    answer3: "Minsk",
    correctAnswer: "Minsk",
    isAnswered: false,
  },
  {
    id: 23,
    question: "Which country is known for its cheese and chocolate?",
    answer1: "Belgium",
    answer2: "Switzerland",
    answer3: "Sweden",
    correctAnswer: "Switzerland",
    isAnswered: false,
  },
  {
    id: 24,
    question:
      "What is the name of the peninsula that is shared by Spain and Portugal?",
    answer1: "Courland Peninsula",
    answer2: "Kola Peninsula",
    answer3: "The Iberian Peninsula",
    correctAnswer: "The Iberian Peninsula",
    isAnswered: false,
  },
  {
    id: 25,
    question:
      "What is the name of the river that flows through Vienna, Austria?",
    answer1: "The Danube River",
    answer2: "Tuna River",
    answer3: "The Loire River",
    correctAnswer: "The Danube River",
    isAnswered: false,
  },
  {
    id: 26,
    question:
      "Which country in Europe is famous for its thermal baths and spas?",
    answer1: "Sweden",
    answer2: "Hungary",
    answer3: "Iceland",
    correctAnswer: "Hungary",
    isAnswered: false,
  },
  {
    id: 27,
    question: "What is the official currency of Poland?",
    answer1: "euro",
    answer2: "złoty",
    answer3: "lira",
    correctAnswer: "złoty",
    isAnswered: false,
  },
  {
    id: 28,
    question:
      "What is the name of the island nation in the Mediterranean that is divided between Greek and Turkish control?",
    answer1: "Greece",
    answer2: "Bulgaria",
    answer3: "Cyprus",
    correctAnswer: "Cyprus",
    isAnswered: false,
  },
  {
    id: 29,
    question:
      "Which country is home to the world's largest particle physics laboratory?",
    answer1: "Switzerland",
    answer2: "United Kingdom",
    answer3: "Germany",
    correctAnswer: "",
    isAnswered: false,
  },
  {
    id: 30,
    question: "Which European country is famous for its fjords?",
    answer1: "Sweden",
    answer2: "Iceland",
    answer3: "Norway",
    correctAnswer: "Norway",
    isAnswered: false,
  },
  {
    id: 31,
    question: "What is the official language of Andorra?",
    answer1: "Spanish",
    answer2: "Catalan",
    answer3: "Portuguese",
    correctAnswer: "Catalan",
    isAnswered: false,
  },
  {
    id: 32,
    question: "What is the capital of Slovakia?",
    answer1: "Bratislava",
    answer2: "Ljubljana",
    answer3: "Cologne",
    correctAnswer: "Bratislava",
    isAnswered: false,
  },
  {
    id: 33,
    question: "Which European city is known as the 'City of Love'?",
    answer1: "Italy",
    answer2: "France",
    answer3: "Greece",
    correctAnswer: "France",
    isAnswered: false,
  },
  {
    id: 34,
    question: "Which country is home to the famous Neuschwanstein Castle?",
    answer1: "Germany",
    answer2: "Austria",
    answer3: "Switzerland",
    correctAnswer: "Germany",
    isAnswered: false,
  },
  {
    id: 35,
    question:
      "Which European country has a flag with a white cross on a red background?",
    answer1: "Vatican City",
    answer2: "Switzerland",
    answer3: "Andorra",
    correctAnswer: "Switzerland",
    isAnswered: false,
  },
  {
    id: 36,
    question: "Which country is home to the famous Ring of Kerry scenic drive?",
    answer1: "Ireland",
    answer2: "Scotland",
    answer3: "Kosovo",
    correctAnswer: "Ireland",
    isAnswered: false,
  },
  {
    id: 37,
    question:
      "Which European country is home to the famous medieval city of Dubrovnik?",
    answer1: "Crotia",
    answer2: "Hungary",
    answer3: "North Macedonia",
    correctAnswer: "Crotia",
    isAnswered: false,
  },
  {
    id: 38,
    question: "What is the capital of Estonia?",
    answer1: "Stockholm",
    answer2: "Oslo",
    answer3: "Tallin",
    correctAnswer: "Tallin",
    isAnswered: false,
  },
  {
    id: 39,
    question: "What is the capital of Serbia?",
    answer1: "Belgrad",
    answer2: "Zagreb",
    answer3: "Stuttgart",
    correctAnswer: "Belgrad",
    isAnswered: false,
  },
  {
    id: 40,
    question: "What is the capital of Belgium?",
    answer1: "Munich",
    answer2: "Brussels",
    answer3: "Istanbul",
    correctAnswer: "Brussels",
    isAnswered: false,
  },
  {
    id: 41,
    question: "Which country does not share a border with Czechia?",
    answer1: "Austria",
    answer2: "Germany",
    answer3: "Slovenia",
    correctAnswer: "Slovenia",
    isAnswered: false,
  },
  {
    id: 42,
    question: "In which city can you find the Manneken Pis?",
    answer1: "Paris",
    answer2: "Brussels",
    answer3: "Helsinki",
    correctAnswer: "Brussels",
    isAnswered: false,
  },
  {
    id: 43,
    question: "How long is Iceland's Ring Road?",
    answer1: "1,078 km",
    answer2: "1,332 km",
    answer3: "1,852 km",
    correctAnswer: "1,332 km",
    isAnswered: false,
  },
  {
    id: 44,
    question: "Which country is not part of the Balkans?",
    answer1: "Croatia",
    answer2: "Montenegro",
    answer3: "Poland",
    correctAnswer: "Poland",
    isAnswered: false,
  },
  {
    id: 45,
    question: "What is the capital of Portugal?",
    answer1: "Lisbon",
    answer2: "Barcelone",
    answer3: "Guimares",
    correctAnswer: "Lisbon",
    isAnswered: false,
  },
  {
    id: 46,
    question: "What is the currency in use in Northern Ireland?",
    answer1: "Euro",
    answer2: "English Dollar",
    answer3: "English Pound",
    correctAnswer: "English Pound",
    isAnswered: false,
  },
  {
    id: 47,
    question: "Which of these countries is closest to Norway?",
    answer1: "Switzerland",
    answer2: "Sweden",
    answer3: "France",
    correctAnswer: "Sweden",
    isAnswered: false,
  },

  {
    id: 48,
    question: "In which European city can you find the Acropolis?",
    answer1: "Sofia",
    answer2: "Rome",
    answer3: "Athens",
    correctAnswer: "Athens",
    isAnswered: false,
  },
  {
    id: 49,
    question: "Uppsala was formerly the capital of which country?",
    answer1: "Denmark",
    answer2: "Norway",
    answer3: "Sweden",
    correctAnswer: "Sweden",
    isAnswered: false,
  },
  {
    id: 50,
    question: "Which of these tiny independent states lies within Rome?",
    answer1: "Vatican City",
    answer2: "Monaco",
    answer3: "Liechtenstein",
    correctAnswer: "Vatican City",
    isAnswered: false,
  },
];
