export default [
  {
    id: 1,
    question: "What is the largest country in North America by area?",
    answer1: "Canada",
    answer2: "U.S.A.",
    answer3: "Mexico",
    correctAnswer: "Canada",
    isAnswered: false,
  },
  {
    id: 2,
    question: "What is the longest river in North America?",
    answer1: "Mississippi River",
    answer2: "Missouri River",
    answer3: "Rio Grande",
    correctAnswer: "Missouri River",
    isAnswered: false,
  },
  {
    id: 3,
    question: "What is the tallest mountain in North America?",
    answer1: "Mount Whitney",
    answer2: "Mount Foraker",
    answer3: "Denali (formerly Mount McKinley)",
    correctAnswer: "Denali (formerly Mount McKinley)",
    isAnswered: false,
  },
  {
    id: 4,
    question:
      "What is the name of the only North American country to have French as its official language?",
    answer1: "Nicaragua",
    answer2: "Canada",
    answer3: "Panama",
    correctAnswer: "Canada",
    isAnswered: false,
  },
  {
    id: 5,
    question:
      "Which country in North America has the highest population density?",
    answer1: "United States",
    answer2: "Canada",
    answer3: "Mexico",
    correctAnswer: "United States",
    isAnswered: false,
  },
  {
    id: 6,
    question: "What is the capital of Mexico?",
    answer1: "Puebla",
    answer2: "Tijuana",
    answer3: "Mexico City",
    correctAnswer: "Mexico City",
    isAnswered: false,
  },
  {
    id: 7,
    question: "What is the name of the largest desert in North America?",
    answer1: "Chihuahuan Desert",
    answer2: "Sonoran Desert",
    answer3: "Mojave Desert",
    correctAnswer: "Chihuahuan Desert",
    isAnswered: false,
  },
  {
    id: 8,
    question: "Which city in North America is known as the 'Windy City'?",
    answer1: "Chicago, United States",
    answer2: "NYC, United States",
    answer3: "Los Angeles, United States",
    correctAnswer: "Chicago, United States",
    isAnswered: false,
  },
  {
    id: 9,
    question: "What is the largest island in North America?",
    answer1: "Prince Patrick Island",
    answer2: "Greenland",
    answer3: "Somerset Island",
    correctAnswer: "Greenland",
    isAnswered: false,
  },
  {
    id: 10,
    question: "What is the capital city of Cuba?",
    answer1: "Havana",
    answer2: "Santa Clara",
    answer3: "Bayamo",
    correctAnswer: "Havana",
    isAnswered: false,
  },
  {
    id: 11,
    question: "What is the official language of Belize?",
    answer1: "Portuguese",
    answer2: "English",
    answer3: "French",
    correctAnswer: "English",
    isAnswered: false,
  },
  {
    id: 12,
    question:
      "What is the name of the mountain range that runs along the west coast of North America",
    answer1: "Mount Lucania",
    answer2: "Rocky Mountains",
    answer3: "Mount Sanford",
    correctAnswer: "Rocky Mountains",
    isAnswered: false,
  },
  {
    id: 13,
    question: "What is the capital of the United States?",
    answer1: "Washington D.C.",
    answer2: "Miami",
    answer3: "Chicago",
    correctAnswer: "Washington D.C.",
    isAnswered: false,
  },
  {
    id: 14,
    question:
      "What is the name of the famous canyon in Arizona, United States?",
    answer1: "Antelope Canyon",
    answer2: "Grand Canyon",
    answer3: "Hells Canyon",
    correctAnswer: "Grand Canyon",
    isAnswered: false,
  },
  {
    id: 15,
    question: "Which country in North America has the smallest land area?",
    answer1: "Barbados",
    answer2: "Martinique",
    answer3: "Saint Kitts and Nevis",
    correctAnswer: "Saint Kitts and Nevis",
    isAnswered: false,
  },
  {
    id: 16,
    question: "What is the name of the tallest waterfall in North America?",
    answer1: "Niagara Falls",
    answer2: "Angel Falls",
    answer3: "McWay Falls",
    correctAnswer: "Angel Falls",
    isAnswered: false,
  },
  {
    id: 17,
    question: "What is the name of the largest city in Canada by population?",
    answer1: "Toronto",
    answer2: "Vancouver",
    answer3: "Montreal",
    correctAnswer: "Toronto",
    isAnswered: false,
  },
  {
    id: 18,
    question:
      "What is the name of the largest city in the United States by population?",
    answer1: "New York City",
    answer2: "San Francisco",
    answer3: "Boston",
    correctAnswer: "New York City",
    isAnswered: false,
  },
  {
    id: 19,
    question:
      "What is the name of the mountain range that runs through the western United States?",
    answer1: "Mount Foraker",
    answer2: "Sierra Nevada Mountains",
    answer3: "Pico de Orizaba",
    correctAnswer: "Sierra Nevada Mountains",
    isAnswered: false,
  },
  {
    id: 20,
    question: "What is the official language of Haiti?",
    answer1: "French and Haitian Creole",
    answer2: "English",
    answer3: "French",
    correctAnswer: "French and Haitian Creole",
    isAnswered: false,
  },
  {
    id: 21,
    question:
      "What is the name of the peninsula in North America that separates the Gulf of Mexico from the Caribbean Sea?",
    answer1: "Tiburon Peninsula",
    answer2: "Maritime Peninsula",
    answer3: "Yucatan Peninsula",
    correctAnswer: "Yucatan Peninsula",
    isAnswered: false,
  },
  {
    id: 22,
    question: "What is the capital of Canada?",
    answer1: "Sydney",
    answer2: "Ottawa",
    answer3: "Ontario",
    correctAnswer: "Ottawa",
    isAnswered: false,
  },
  {
    id: 23,
    question: "What is the name of the largest river in Mexico?",
    answer1: "Rio Grande",
    answer2: "Colorado River",
    answer3: "Balsas River",
    correctAnswer: "Rio Grande",
    isAnswered: false,
  },
  {
    id: 24,
    question: "What is the capital city of Honduras?",
    answer1: "La Ceiba",
    answer2: "Tegusigalpa",
    answer3: "Choluteca",
    correctAnswer: "Tegusigalpa",
    isAnswered: false,
  },
  {
    id: 25,
    question: "What is the capital city of Jamaica?",
    answer1: "Montego Bay",
    answer2: "Portmore",
    answer3: "Kingston",
    correctAnswer: "Kingston",
    isAnswered: false,
  },
];
