export default [
  {
    id: 1,
    question: "What is the largest country in Oceania by area? ",
    answer1: "Australia",
    answer2: "Vanuatu",
    answer3: "Tuvalu",
    correctAnswer: "Australia",
    isAnswered: false,
  },
  {
    id: 2,
    question: "What is the smallest country in Oceania by area?",
    answer1: "Fiji",
    answer2: "Nauru",
    answer3: "Kiribati",
    correctAnswer: "Nauru",
    isAnswered: false,
  },
  {
    id: 3,
    question: "What is the capital of New Zealand?",
    answer1: "Auckland",
    answer2: "Hamilton",
    answer3: "Wellington",
    correctAnswer: "Wellington",
    isAnswered: false,
  },
  {
    id: 4,
    question: "What is the largest city in Australia?",
    answer1: "Sydney",
    answer2: "Melbourne",
    answer3: "Brisbane",
    correctAnswer: "Sydney",
    isAnswered: false,
  },
  {
    id: 5,
    question: "What is the highest mountain in Australia?",
    answer1: "Bluff Knoll",
    answer2: "Mount Kosciuszko",
    answer3: "Mount Augustus",
    correctAnswer: "Mount Kosciuszko",
    isAnswered: false,
  },
  {
    id: 6,
    question: "What is the capital of Papua New Guinea?",
    answer1: "Port Moresby",
    answer2: "Goroka",
    answer3: "Rabaul",
    correctAnswer: "Port Moresby",
    isAnswered: false,
  },
  {
    id: 7,
    question: "What is the highest mountain in Africa?",
    answer1: "Mount Kilimanjaro",
    answer2: "Mount Meru",
    answer3: "Mount Guna",
    correctAnswer: "Mount Kilimanjaro",
    isAnswered: false,
  },
  {
    id: 8,
    question: "What is the largest island in Oceania? ",
    answer1: "Micronesia",
    answer2: "Samoa",
    answer3: "New Guinea",
    correctAnswer: "New Guinea",
    isAnswered: false,
  },
  {
    id: 9,
    question: "What is the highest mountain in New Zealand?",
    answer1: "Mount Ngauruhoe",
    answer2: "Mount Cook",
    answer3: "Mount Taranaki",
    correctAnswer: "Mount Cook",
    isAnswered: false,
  },
  {
    id: 10,
    question: "What is the largest lake in Australia?",
    answer1: "Lake Eacham",
    answer2: "Lake Eyre",
    answer3: "Lake McKenzie",
    correctAnswer: "Lake Eyre",
    isAnswered: false,
  },
  {
    id: 11,
    question: "What is the capital of Vanuatu?",
    answer1: "Luganville",
    answer2: "Isangel",
    answer3: "Port Vila",
    correctAnswer: "Port Vila",
    isAnswered: false,
  },
  {
    id: 12,
    question: "What is the largest city in New Zealand?",
    answer1: "Wellington",
    answer2: "Auckland",
    answer3: "Nelson",
    correctAnswer: "Auckland",
    isAnswered: false,
  },
  {
    id: 13,
    question:
      "What is the name of the largest island in the Solomon Islands archipelago?",
    answer1: "Guadalcanal Island",
    answer2: "Lord Howe Island",
    answer3: "Norfolk Island",
    correctAnswer: "Guadalcanal Island",
    isAnswered: false,
  },
  {
    id: 14,
    question:
      "Which country in Oceania is the only one that spans both the eastern and western hemispheres?",
    answer1: "Tuvalu",
    answer2: "Kiribati ",
    answer3: "Marshall Islands",
    correctAnswer: "Kiribati",
    isAnswered: false,
  },
  {
    id: 15,
    question:
      "What is the name of the active volcano in Vanuatu that is known for its frequent eruptions?",
    answer1: "Bagana",
    answer2: "Tinakula",
    answer3: "Yasur Volcano",
    correctAnswer: "Yasur Volcanor",
    isAnswered: false,
  },
  {
    id: 16,
    question:
      "Which island country in Oceania is the smallest in terms of land area?",
    answer1: "Gulf of Aden",
    answer2: "Nauru",
    answer3: "Tuvalu",
    correctAnswer: "Palau",
    isAnswered: false,
  },
  {
    id: 17,
    question:
      "What is the name of the strait that separates Australia and Papua New Guinea?",
    answer1: "Torres Strait",
    answer2: "Somosomo Strait",
    answer3: "Tiputa Pass",
    correctAnswer: "Torres Strait",
    isAnswered: false,
  },
  {
    id: 18,
    question:
      "What is the name of the island country in Oceania that is home to the world's largest raised coral atoll?",
    answer1: "Rennell Island",
    answer2: "Solomon Islands",
    answer3: "Marshall Islands",
    correctAnswer: "Rennell Island",
    isAnswered: false,
  },
  {
    id: 19,
    question: "What is the capital city of Fiji?",
    answer1: "Suva",
    answer2: "Labasa",
    answer3: "Nadi",
    correctAnswer: "Suva",
    isAnswered: false,
  },
  {
    id: 20,
    question: "What is the capital city of Micronesia?",
    answer1: "Tofol",
    answer2: "Palikir",
    answer3: "Palikir",
    correctAnswer: "Palikir",
    isAnswered: false,
  },
];
