export default [
  {
    id: 1,
    question:
      "Which South American city is overlooked by a granite peak known as Sugar Loaf?",
    answer1: "Lima",
    answer2: "Rio de Janeiro",
    answer3: "Buenos Aires",
    correctAnswer: "Rio de Janeiro",
    isAnswered: false,
  },
  {
    id: 2,
    question: "Which South American country does not border the Pacific Ocean?",
    answer1: "Peru",
    answer2: "Colombia",
    answer3: "Brazil",
    correctAnswer: "Brazil",
    isAnswered: false,
  },
  {
    id: 3,
    question: "What is the highest peak in South America?",
    answer1: "Mount Rushmore",
    answer2: "Mount Aconcagua",
    answer3: "Denali",
    correctAnswer: "Mount Aconcagua",
    isAnswered: false,
  },
  {
    id: 4,
    question: "Which country in South America is the largest by land area? ",
    answer1: "Brazil",
    answer2: "Argentina",
    answer3: "Colombia",
    correctAnswer: "Brazil",
    isAnswered: false,
  },
  {
    id: 5,
    question: "What is the name of the largest river in South America? ",
    answer1: "Orinoco River",
    answer2: "Amazon River",
    answer3: "Wenamu River",
    correctAnswer: "Amazon River",
    isAnswered: false,
  },
  {
    id: 6,
    question: "Which South American country has the longest coastline?",
    answer1: "Chile",
    answer2: "Peru",
    answer3: "Ecuador",
    correctAnswer: "Chile",
    isAnswered: false,
  },
  {
    id: 7,
    question:
      "What is the name of the famous waterfall located on the border of Argentina and Brazil? ",
    answer1: "Yumbilla Falls",
    answer2: "Tequendama Falls",
    answer3: "Iguazu Falls",
    correctAnswer: "Iguazu Falls",
    isAnswered: false,
  },
  {
    id: 8,
    question:
      "What is the name of the driest desert in the world, located in Chile?",
    answer1: "Atacama Desert",
    answer2: "Mojave Desert",
    answer3: "Sonoran Desert",
    correctAnswer: "Atacama Desert",
    isAnswered: false,
  },
  {
    id: 9,
    question:
      "Which South American country is home to the largest salt flat in the world?",
    answer1: "Uruguay",
    answer2: "Bolivia",
    answer3: "Colombia",
    correctAnswer: "Bolivia",
    isAnswered: false,
  },
  {
    id: 10,
    question:
      "What is the name of the mountain range that runs through much of South America?",
    answer1: "Aconcagua",
    answer2: "Andes Mountains",
    answer3: "Mercedario",
    correctAnswer: "Andes Mountains",
    isAnswered: false,
  },
  {
    id: 11,
    question:
      "Which South American country has a capital city named Montevideo?",
    answer1: "Venezuela",
    answer2: "Guyana",
    answer3: "Uruguay",
    correctAnswer: "Uruguay",
    isAnswered: false,
  },
  {
    id: 12,
    question:
      "Which South American country has two capital cities, La Paz and Sucre?",
    answer1: "Bolivia",
    answer2: "Suriname",
    answer3: "Falkland Islands",
    correctAnswer: "Bolivia",
    isAnswered: false,
  },
  {
    id: 13,
    question:
      "What is the name of the famous wine region located in Argentina?",
    answer1: "Tabata",
    answer2: "Mendoza",
    answer3: "Guti",
    correctAnswer: "Mendoza",
    isAnswered: false,
  },
  {
    id: 14,
    question:
      "Which South American country is home to the world's largest rainforest?",
    answer1: "Brazil",
    answer2: "Argentina",
    answer3: "Peru",
    correctAnswer: "Brazil",
    isAnswered: false,
  },
  {
    id: 15,
    question: "What is the capital city of Brazil?",
    answer1: "Sao Paulo",
    answer2: "Curitiba",
    answer3: "Brasilia",
    correctAnswer: "Brasilia",
    isAnswered: false,
  },
  {
    id: 16,
    question: "What is the capital city of Peru?",
    answer1: "Lima",
    answer2: "Cusco",
    answer3: "Cajamarca",
    correctAnswer: "Lima",
    isAnswered: false,
  },
  {
    id: 17,
    question: "What is the capital city of Argentina?",
    answer1: "Mendoza",
    answer2: "Buenos Aires",
    answer3: "Rosario",
    correctAnswer: "Buenos Aires",
    isAnswered: false,
  },
  {
    id: 18,
    question: "What is the capital city of Paraguay?",
    answer1: "Aregua",
    answer2: "Encarnacion",
    answer3: "Asunsion",
    correctAnswer: "Asunsion",
    isAnswered: false,
  },
  {
    id: 19,
    question: "What is the capital city of Venezuela?",
    answer1: "Karakas",
    answer2: "Maracay",
    answer3: "Maturin",
    correctAnswer: "Karakas",
    isAnswered: false,
  },
  {
    id: 20,
    question: "What is the capital city of Micronesia?",
    answer1: "Cali",
    answer2: "Medellin",
    answer3: "Bogota",
    correctAnswer: "Bogota",
    isAnswered: false,
  },
];
