const tr = {
  continentAsia: "Asya",
  continentEurope: "Avrupa",
  continentAfrica: "Afrika",
  continentNorthAmerica: "Kuzey Amerika",
  continentSouthAmerica: "Güney Amerika",
  continentOceania: "Okyanusya",
  gameHistoryTitle: "Oyun Geçmişi",
  flagQuiz: "Bayrak Bilmece",
  geoQuiz: "Genel Kültür",
  dateLabel: "Tarih",
  trueLabel: "Doğru Cevaplar:",
  falseLabel: "Yanlış Cevaplar",
  backLabel: "Geri",
  nextLabel: "İleri",
  continentPlaceHolder: "Oynamak için bir kıta seç!",
  gameTypePlaceHolder: "Oyun tipini seç",
  challengePlaceHolder: "Son olarak meydan okuma modunu seç!",
  startGameLabel: "Oyunu Başlat",
  timeTrail: "Zamana Karşı",
  liveGame: "3-Can",
  exitLabel: "Oyunu Terk et",
};

const en = {
  continentAsia: "Asia",
  continentEurope: "Europe",
  continentAfrica: "Africa",
  continentNorthAmerica: "North America",
  continentSouthAmerica: "South America",
  continentOceania: "Oceania",
  gameHistoryTitle: "Game History",
  flagQuiz: "Flag Quiz",
  geoQuiz: "Geo Quiz",
  dateLabel: "Date",
  trueLabel: "True Answers:",
  falseLabel: "False Answers:",
  backLabel: "Back",
  nextLabel: "Next",
  continentPlaceHolder: "Select a continent to play!",
  gameTypePlaceHolder: "Select a game type",
  challengePlaceHolder: "Lastly select your challenge!",
  startGameLabel: "Start the game",
  timeTrail: "Time Trail",
  liveGame: "3-Lives",
  exitLabel: "Exit the session",
};

export { tr, en };
