const tr = {
  continentAsia: "Asya",
  continentEurope: "Avrupa",
  continentAfrica: "Afrika",
  continentNorthAmerica: "Kuzey Amerika",
  continentSouthAmerica: "Güney Amerika",
  continentOceania: "Okyanusya",
  gameHistoryTitle: "Oyun Geçmişi",
  settingsTitle: "Ayarlar",
  flagQuiz: "Bayrak Bilmece",
  geoQuiz: "Genel Kültür",
  dateLabel: "Tarih",
  trueLabel: "Doğru Cevaplar: ",
  falseLabel: "Yanlış Cevaplar: ",
  statisticsTrue: "Doğru",
  statisticsFalse: "Yanlış",
  backLabel: "Geri",
  nextLabel: "İleri",
  continentPlaceHolder: "Oynamak için bir kıta seç!",
  gameTypePlaceHolder: "Oyun tipini seç",
  challengePlaceHolder: "Son olarak meydan okuma modunu seç!",
  startGameLabel: "Oyunu Başlat",
  timeTrail: "Zamana Karşı",
  liveGame: "3-Can",
  exitLabel: "Oyunu Terk et",
  backToHome: "Ana sayfaya dön",
  changeLang: "Dili Değiştir",
  changeTheme: "Tema Değiştir",
  lightLabel: "Aydınlık",
  darkLabel: "Karanlık",
  trueAnswer: "Doğru Cevap",
  falseAnswer: "Senin cevabın",
  question: "Soru",
  finishingTitle: "Oyun bitti!",
  trueLabel: "Doğru sayısı: ",
  falseLabel: "Yanlış sayısı: ",
  deleteTitle: "Oyun geçmişi silinecek",
  deleteButtonTitle: "Oyun geçmişini sil",
  deleteText: "Geri dönüşü yok emin misin?",
  yesLabel: "Evet, Sil",
  noLabel: "Hayır",
};

const en = {
  continentAsia: "Asia",
  continentEurope: "Europe",
  continentAfrica: "Africa",
  continentNorthAmerica: "North America",
  continentSouthAmerica: "South America",
  continentOceania: "Oceania",
  gameHistoryTitle: "Game History",
  settingsTitle: "Settings",
  flagQuiz: "Flag Quiz",
  geoQuiz: "Geo Quiz",
  dateLabel: "Date",
  trueLabel: "True Answers:",
  falseLabel: "False Answers:",
  statisticsTrue: "True",
  statisticsFalse: "False",
  backLabel: "Back",
  nextLabel: "Next",
  continentPlaceHolder: "Select a continent to play!",
  gameTypePlaceHolder: "Select a game type",
  challengePlaceHolder: "Lastly select your challenge!",
  startGameLabel: "Start the game",
  timeTrail: "Time Trail",
  liveGame: "3-Lives",
  exitLabel: "Exit the session",
  backToHome: "Back to home",
  changeTheme: "Change Theme",
  lightLabel: "Light",
  darkLabel: "Dark",
  trueAnswer: "True answer",
  falseAnswer: "Your answer",
  question: "Question",
  finishingTitle: "Game Over!",
  trueLabel: "True answer count: ",
  falseLabel: "False answer count: ",
  deleteButtonTitle: "Delete history",
  deleteTitle: "Game history going to be deleted",
  deleteText: "Are you sure?",
  yesLabel: "Yes, Delete",
  noLabel: "No",
};

export { tr, en };
